apiVersion: v1
kind: Pod
metadata:
  name: giropops
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - name: giros
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 0.5
        memory: 128Mi
      requests:
        cpu: 0.25
        memory: 64Mi
